### ISSUE TITLE
[Feature] Dynamic supervisor and Registry

### ISSUE THREAD

**Issue by sungchulTW** [leostera/riot#13]
Hello.

I think Riot has a lot of potential.
GenServer in OCaml is a good mix.

While Riot is good as-is, dynamic supervisors and registry can be good additions.
But I guess, the typed registry can be difficult as we see Gleam (typed Erlang) sees same problem.

Thank you.

**Comment by leostera** [comment]
@sungchul-twinny thanks for opening this! I just pushed https://github.com/leostera/riot/commit/249327007d6029e26512f38e4699f96a09441b01 adding rudimentary support for globally registering processes by name, and the possibility to send a message by name instead of by pid.

This should help us register supervisors by name and send them `Spawn_child` messages later on,  to build dynamic supervisors.

Can you share a bit more about the Registry? Did you mean the Elixir's Registry module?

**Comment by leostera** [comment]
@sungchulTW we ended up implementing a small `Dynamic_supervisor` that we can extend to support more use-cases. It is currently functioning on `main`, and should be released as part of riot 0.0.8 – let me know what you think :)

**Comment by leostera** [comment]
Closing this for now, but @sungchulTW please reopen if the Dynamic_usperivsor and process registering features we have are missing something. Thanks for opening the issue! ✨
